// Writes src/environments/environment.ts from the API_BASE_URL env var (default '/api').
// Runs as part of `npm run build`, so the backend URL is chosen per deployment without hardcoding.
import { writeFileSync } from 'node:fs';

const apiBaseUrl = process.env.API_BASE_URL ?? '/api';

const content = `// Generated by set-env.mjs at build time from the API_BASE_URL env var (default '/api').
export const environment = {
  apiBaseUrl: '${apiBaseUrl}',
};
`;

writeFileSync(new URL('./src/environments/environment.ts', import.meta.url), content);
console.log(`environment.ts written with apiBaseUrl='${apiBaseUrl}'`);
